// ==UserScript==
// @name        Text to Mail
// @namespace	github.com/heussd/texttomail
// @description	Allows to e-mail pages that are viewed in reader mode.
// @include     about:reader?url=*
// @version     1.0
// ==/UserScript==
var mailAddress = '';

// This userscript is called multiple times. The following makes sure that the primary control button is only added once.
if (document.getElementById('mailtotext') == undefined) {
  var button = document.createElement('button');
  button.setAttribute("id", "mailtotext");
  button.setAttribute('onclick', 'mailThisPage("' + mailAddress + '")');
  button.appendChild(document.createTextNode('✉️'));
  button.className = 'button';
  button.style.fontSize = "17pt";

  var ul = document.createElement('ul');
  ul.className = 'dropdown';
  ul.appendChild(button);

  var toolbar = document.getElementById('reader-toolbar');
  toolbar.appendChild(ul);

  var script = document.createElement('script');

  // Use ECMAScript 6 template literals to embed the code to process the reader view content. This is necessary because Firefox' reader view itself is generated by JavaScript during runtime, so collecting the resulting text output must happen after that.
  var embeddedScript = `
  function cleanText(text) {
    text = text.trim();
    text = text.replace(/^\s+|\s+$/gm,"\\n");
    return text;
  }

  function recursiveChildCollector(elements, text) {
    if (elements.textContent != undefined) {
      text = text + "\\n" + cleanText(elements.textContent);
    }
    for (var i = 0; i < elements.length; i++) {
      var child = elements[i];
      text = text + recursiveChildCollector(child, text);
    }
    return "\\n" + cleanText(text);
  }

  function mailThisPage(mailAddress) {
    url = document.getElementById("reader-domain").getAttribute("href");
    title = document.getElementById("reader-title").innerHTML;

    var elements = document.getElementById("moz-reader-content").childNodes;
    content = recursiveChildCollector(elements, "");

    window.open("mailto:" + mailAddress + "?subject="+encodeURIComponent(title)+"&body=" + encodeURIComponent(url + "\\n\\n" + content), "_self");
  }
  `;
  script.appendChild(document.createTextNode(embeddedScript));
  toolbar.appendChild(script);
}
